name: Test Dispatch
on: workflow_dispatch

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test repository dispatch
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2
        with:
          # token: ${{ secrets.PUBLIC_REPO_SCOPED_TOKEN }}
          event-type: tests
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
